version: '2.3'

services:
  webrtc:
    build: .
    environment:
      - TZ=Asia/Seoul
    
    ports:
      - 8088:8088

    volumes: 
      - ./signaling:/opt/signaling
      # - /home/du9172/.vscode-server/extensions/:/root/.vscode-server/extensions/
    tty: true
    
    command: /bin/bash 

  

